### ISSUE TITLE
time data does not match

### ISSUE THREAD

**Issue by scollier** [jobbler/cdn_reports#1]
I keep running out of subscriptions with my cdn account.  Here's what I'm seeing when I try to query the cdn API:

```
$ ./cdn_report.py --poolusage --user <username> --password <password>- --ownerid <ownerid>
Getting list of pools from CDN.
Getting list of hosts from CDN.
Traceback (most recent call last):
  File "./cdn_report.py", line 234, in <module>
    secs_create = datetime.strptime(ckey["created"], "%Y-%m-%dT%H:%M:%S.000+0000").strftime("%s")
  File "/usr/lib64/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib64/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '2015-04-29t17:43:19+0000' does not match format '%Y-%m-%dT%H:%M:%S.000+0000'
```

Here's what I have installed:

```
$ rpm -q python3-natsort python3
python3-natsort-5.0.3-1.fc26.noarch
python3-3.6.4-2.fc26.x86_64
```

**Comment by ghost** [comment]
Hello,

I had the same issue and sent in a PR which fixed it for me.

Thanks.
